version: '3.8'

services:
  cassandra:
    image: cassandra
    container_name: cassandra
    ports:
      - "9042:9042" # CQL native transport port
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep UN"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  cassandra_data: